require('sinatra')
require('sinatra/contrib/all')
require('date')
require_relative('models/pet')
require_relative('models/customer')
require_relative('controllers/customers')
require_relative('controllers/pets')